language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
    env: NUMBA="false" "PATH=~/bin:$PATH"
  - python: 3.5
    env: NUMBA="false" "PATH=~/bin:$PATH"
  - python: 3.6
    env: NUMBA="false" "PATH=~/bin:$PATH"
  - python: 2.7
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" "PATH=~/bin:$PATH"
  - python: 3.5
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" "PATH=~/bin:$PATH"
  - python: 3.6
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" "PATH=~/bin:$PATH"
before_install:
  - >
    if [ "${NUMBA}" == "true" ]; then
      travis/install_clang38.sh;
      travis/install_llvmlite.sh;
    fi
  - travis/install_pandoc.sh
script:
  - python setup.py sdist bdist_wheel
  - >
    if [ "${NUMBA}" == "true" ]; then
      pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`[numba];
    else
      pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`;
    fi
  - pushd /
  - python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"
  - popd
notifications:
  email: false
deploy:
  provider: pypi
  skip_upload_docs: true
  skip_cleanup: true
  user: dhorta
  password:
    secure: UJAvFuRc8RRB5PBdGw1dzWLhpF2XV54DEIQ8bTvdCBX1icYY4WVkplaI6VhEaxn6jCfk7gMxXI1bFOMpJh4iVkUtnpEbhgZbMsxwcPFL5BuPbaeOSpxNBD/QAQQQFPZSz+zeEThZmf+InrXxxMoi7dVQXIC60dMMr05/tm87lOYjALdsUKc+0XdQ0mmEAcgueD1cuHaXgD6eECdb+taXMaw1Or/r+8Oq9fXntMfb+ZbsYrMZCarP4UwW4tJr81IEJOltH6caleI6YX6bcnqpnm1HraqN74Atw0zNMNqPKkbTZv2hdIWRWyGkEjOcwXDAiOMK/vwB8K5Hqf24hAIZAwgDHcKfy1n7FKeiO9xk2XVnwswUvmJSCgWENcZ++5unfDLjC+pMEpzvw0NkfTzGiiDiOx91RALvslAosYy8xKHc22YO7gvggcQfXyMh5AlCLZWdlcgJlUBFNHmKMGRbTom1lB3Eol0XisDBfoO0/1QQ5GTuD9J1JY7CBYzFP033RI/GjD+fedZYKnuHwQdDpvFmcXK7wc+NDNlTNWYTZ3U4s1BvQh/XFMUAYwxVnOUF7Tu+DOiGjiOTGDuH7CzkvD8WMgNtGxtDcbMfIXZoKG6ylY3ilfpCIlvPRX51ctTHhQyB6roMIV8uSt1+RhbFZudKw4KS5Hyqkm9niWPfKFo=
  on:
    distributions: sdist
    repo: glimix/numpy-sugar
