language: python
sudo: required
dist: trusty
git:
  depth: 5
before_install:
- sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8
  main' || true
- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - || true
- sudo apt-get update -y || true
- sudo apt-get install -qq -y clang-3.8 zlib1g-dev libbz2-dev || true
matrix:
  include:
  - os: linux
    python: '2.7'
    compiler: clang-3.8
    env: LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
  - os: linux
    python: '3.5'
    compiler: clang-3.8
    env: LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
script:
- pip install pypandoc
- git clone https://github.com/numba/llvmlite.git --depth 1
- pushd llvmlite
- CXX_FLTO_FLAGS= LD_FLTO_FLAGS= python setup.py install
- popd
- python -c "from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');"
- export PATH=~/bin:$PATH
- ~/bin/pandoc -v
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import numpy_sugar; numpy_sugar.test()"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  skip_upload_docs: true
  user: dhorta
  on:
    distributions: sdist bdist_wheel
    repo: glimix/numpy-sugar
