language: python
sudo: false
python: 3.6
env:
- PKG_NAME=numpy_sugar
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: hZqmEfAsVgW7hjj1ydhwBYt9O0F94RZPdIQZ6aTC1Pc3S2B3KAc5boOC0PB1TDBU71hWXGgsajtFctEBndVA2ewz07r1KRXUW5SAyS6D1S6x8dVRjapGgqF5bZuStKeQXjfi43Fkad0uEkSNZFdt/SD2QXxsj7kr1MnRO5HsS816/kwwRNUtB/XTqndrdoHT/ewEp0l20MfNo2c0T+VZy7Hu/koDx198wYid7eQFkHa+Mpiw7339BHG6jrDNwGC470chry+f+GSBATqaggIL2wbvdecSL/62z3FopxSdDbWErflTXxZnTeWuCCOyulx7rwvViC4PWk8LO6I/z7Ptf2kG93LkCt3Q8yAfSJ07BbRtx6A8scIdzBJk8jpUsLvPIjEp1soz/qvh9x2Y1+nikYsFC/uwsZ96+cT4WVIN6LwUpeNjj3Uyp5+puG98JXa60GgmUbeHtGVOY+pE7HV6qYdCCNSFE2oVEJv1xk4uTjMg+vRb0BPEg1xZkLzweHpjDdyorYF0HaDSUQe1GTk2vCAn6hrYE9afNNFmQE+lEOrBhIIlTb8gAcBmBndyNOZDZuA+cZLQ9xpLzBnhYQw1qBQaU7ochM5uDKRsk20v+sYMVirxcUAFfIt5rsu8ZwzZdajY17gs5TJyVoeBEYTufsK/+Bm7ewiF/u3ovlPx1b4=
  on:
    tags: true
    repo: limix/numpy-sugar
    branch: master
    python: 3.6
