language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
    env: NUMBA="false" "PATH=~/bin:$PATH"
  - python: 3.5
    env: NUMBA="false" "PATH=~/bin:$PATH"
  - python: 3.6
    env: NUMBA="false" "PATH=~/bin:$PATH"
  - python: 2.7
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
      "PATH=~/bin:$PATH"
  - python: 3.5
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
      "PATH=~/bin:$PATH"
  - python: 3.6
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
      "PATH=~/bin:$PATH"
before_install:
- |
  if [ "${NUMBA}" == "true" ]; then
    travis/install_clang38.sh;
    travis/install_llvmlite.sh;
  fi
- travis/install_pandoc.sh
script:
- python setup.py sdist
- |
  if [ "${NUMBA}" == "true" ]; then
    pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`[numba];
  else
    pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`;
  fi
- pushd /
- python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: dKPhQxlgHMxwNZmDt8gbDxLOc2plbwhYBxlY5PXS+fGtIm+v8aMbWkwhiIRCyeUjo0AnYm/+L2RXWL++zetfaPJ5pq3L1wWL8YmjA7UnC4+tsySqdHRRudbDyKBvrhfx2ON8d7JQlw8jJFHWNZJnFA1Vlx6u6PUNp+R0r+LrrawrFlYTPsRBz7GOcy2sj0/sD70GNUP3k3aca58nRDnXb1v5IkUlTM9l4Tx7oYLzK9JjPxMQkLAG+ONikkIpC4xu3TkXyAdUAGyNTFSbhINW4ehILutz/oNNhZeCuVA9qHeAw00BXzjrYBRdHt44WZW1oS+9uV2MU+A/3XeMAjIAc5w8SZ/o+XAhdY5PrWEcI3IE0Nm3aazvMHH6xVBVoWG549GGIY83sQk80Rha4ihSKKOowib0tIa32ownIzCgmQ6xojDV6WD7anNioyAtikVOo+hYmcnU6CoBmPQTVAE19u/W0LtwIihMWGuKQtmVdbU24prWrZA8dGJ3uBrDVfiuqCC3ozS5ZR9a4jn6JCMjH/hGUibB0yqMY/B8HgZtOP70g8dMku+2Z6EYbugKet6C8gOIsm79TV3nYcpChAl/fhWFhx52/ZcnVVup1OdDQO+uEawm8UG3ESjAVCxZURGWnUl0QIosWd150eqLR8SwQ+GbVqqD3YKGxP3livMnRvw=
  on:
    repo: limix/numpy-sugar
    branch: 1.0.x
